This notebook is for generating the tuning curves of the neurons in the visual system for the Mind Field show.  Use at your own risk, MIT License. C. Eliasmith.

In [1]:
import numpy as np

def print_layer(layer):
    for i, row in enumerate(layer):
        print(i+1)
        print(row.reshape(5,5))    

###########################
#one person per pixel in a 5x5 array - Retina
###########################
retina = np.diag(np.ones(25))
#print_layer(retina)

###########################
#horizontal line segments - V1
###########################
v1_hor_ind = np.array([[0,1,2],[1,2,3],[2,3,4]])
v1_hor = []

for i in range(5):
    for j in range(3):
        tmp = np.zeros(25)
        tmp[v1_hor_ind[j]] = 1
        v1_hor.append(tmp)
    v1_hor_ind += 5
#print_layer(v1_hor)
    
###########################
#verticle line segments - V1
###########################
v1_vert_ind = np.array([[0,5,10],[5,10,15],[10,15,20]])
v1_vert = []

for i in range(5):
    for j in range(3):
        tmp = np.zeros(25)
        tmp[v1_vert_ind[j]] = 1
        v1_vert.append(tmp)
    v1_vert_ind += 1
#print_layer(v1_vert)

v1 = np.concatenate((v1_hor, v1_vert))

In [2]:
###########################
#full height straight lines - V2
###########################
v1_bar_ind = np.array(range(0,25,5))
#print(v1_bar_ind)

v1_bar = []

for i in range(5):
    tmp = np.zeros(25)
    tmp[v1_bar_ind] = 1
    v1_bar.append(tmp)
    v1_bar_ind += 1
#print_layer(v1_bar)

###########################
#corners - V2
###########################
v2_top_r_ind = [0,1,2,7,12]
v2_top_l_ind = [0,1,2,5,10]
v2_bot_r_ind = [2,7,10,11,12]
v2_bot_l_ind = [0,5,10,11,12]

def gen_corners(inds):
    matrices = []
    inds = np.array(inds)
    for i in range(2):
        for j in range(3):
            tmp = np.zeros(25)
            tmp[inds] = 1
            matrices.append(tmp)
            inds += 1
        inds += 7
    return matrices

v2_top_r = gen_corners(v2_top_r_ind)
v2_top_l = gen_corners(v2_top_l_ind)
v2_bot_r = gen_corners(v2_bot_r_ind)
v2_bot_l = gen_corners(v2_bot_l_ind)

#print_layer(v2_top_r)
#print_layer(v2_top_l)
#print_layer(v2_bot_r)
#print_layer(v2_bot_l)
v2 = np.concatenate((v2_top_r,v2_top_l,v2_bot_r,v2_bot_l))

In [3]:
###########################
#define number templates - V4
###########################

one_c = np.zeros(25)
one_c[np.array(range(0,25,5))+2] = 1
one_c = one_c.reshape(5,5)
two_c = [[ 0.,  1.,  1.,  1.,  0.],
         [ 0.,  0.,  0.,  1.,  0.],
         [ 0.,  1.,  1.,  1.,  0.],
         [ 0.,  1.,  0.,  0.,  0.],
         [ 0.,  1.,  1.,  1.,  0.]]

three_c = [[ 0.,  1.,  1.,  1.,  0.],
           [ 0.,  0.,  0.,  1.,  0.],
           [ 0.,  0.,  1.,  1.,  0.],
           [ 0.,  0.,  0.,  1.,  0.],
           [ 0.,  1.,  1.,  1.,  0.]]

four_c = [[ 0.,  1.,  0.,  1.,  0.],
          [ 0.,  1.,  0.,  1.,  0.],
          [ 0.,  1.,  1.,  1.,  0.],
          [ 0.,  0.,  0.,  1.,  0.],
          [ 0.,  0.,  0.,  1.,  0.]]

five_c = [[ 0.,  1.,  1.,  1.,  0.],
          [ 0.,  1.,  0.,  0.,  0.],
          [ 0.,  1.,  1.,  1.,  0.],
          [ 0.,  0.,  0.,  1.,  0.],
          [ 0.,  1.,  1.,  1.,  0.]]

six_c = [[ 0.,  1.,  0.,  0.,  0.],
         [ 0.,  1.,  0.,  0.,  0.],
         [ 0.,  1.,  1.,  1.,  0.],
         [ 0.,  1.,  0.,  1.,  0.],
         [ 0.,  1.,  1.,  1.,  0.]]

seven_c = [[ 0.,  1.,  1.,  1.,  0.],
           [ 0.,  0.,  0.,  1.,  0.],
           [ 0.,  0.,  0.,  1.,  0.],
           [ 0.,  0.,  0.,  1.,  0.],
           [ 0.,  0.,  0.,  1.,  0.]]

eight_c = [[ 0.,  1.,  1.,  1.,  0.],
           [ 0.,  1.,  0.,  1.,  0.],
           [ 0.,  1.,  1.,  1.,  0.],
           [ 0.,  1.,  0.,  1.,  0.],
           [ 0.,  1.,  1.,  1.,  0.]]

nine_c = [[ 0.,  1.,  1.,  1.,  0.],
          [ 0.,  1.,  0.,  1.,  0.],
          [ 0.,  1.,  1.,  1.,  0.],
          [ 0.,  0.,  0.,  1.,  0.],
          [ 0.,  0.,  0.,  1.,  0.]]

zero_c = [[ 0.,  1.,  1.,  1.,  0.],
          [ 0.,  1.,  0.,  1.,  0.],
          [ 0.,  1.,  0.,  1.,  0.],
          [ 0.,  1.,  0.,  1.,  0.],
          [ 0.,  1.,  1.,  1.,  0.]]

one_ll = np.array(np.roll(one_c.reshape(1,25), -2))
one_l = np.array(np.roll(one_c.reshape(1,25), -1))
one_r = np.array(np.roll(one_c.reshape(1,25), 1))
one_rr = np.array(np.roll(one_c.reshape(1,25), 2))
one_c = one_c.reshape(1,25)
one = np.concatenate((one_ll, one_l, one_c, one_r, one_rr))

def gen_num_mat(num):
    return np.squeeze(
            np.array(
                [np.roll(num.reshape(1,25), -1), num.reshape(1,25), np.roll(num.reshape(1,25), 1)]
            )
           )

two = gen_num_mat(np.array(two_c))
three = gen_num_mat(np.array(three_c))
four = gen_num_mat(np.array(four_c))
five = gen_num_mat(np.array(five_c))
six = gen_num_mat(np.array(six_c))
seven = gen_num_mat(np.array(seven_c))
eight = gen_num_mat(np.array(eight_c))
nine = gen_num_mat(np.array(nine_c))
zero = gen_num_mat(np.array(zero_c))

v4 = np.concatenate((one, two, three, four, five, six, seven, eight, nine, zero))

In [4]:
###########################
#Number classification - IT
###########################
# Just get inputs from V4 and map to digits

In [5]:
###########################
#Print the entire set of feature detectors
###########################

all_features = np.concatenate((retina, v1, v2, v4))

print_layer(all_features)




1
[[1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
2
[[0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
3
[[0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
4
[[0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
5
[[0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
6
[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
7
[[0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
8
[[0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
9
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
10
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
11
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 0. 0. 0